# -*- coding: utf-8 -*-
"""AryanKate_QuantumIT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4zlGjlHPDhs4DG427hVbiIht8Keceaa
"""

# ─────────────────────────────────────────────
# 0. Environment Setup
# ─────────────────────────────────────────────
# Run once in Colab / shell before importing:
#   pip install kaggle torchvision pytorch-fid --quiet

import os
import math
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torchvision.utils import save_image, make_grid
from torchvision.datasets import ImageFolder
from torchvision.models import inception_v3
from torch.utils.data import DataLoader, Subset
from scipy import linalg
from tqdm import tqdm


# ─────────────────────────────────────────────
# 1. Hyper-parameters
# ─────────────────────────────────────────────
IMAGE_SIZE        = 64       # Spatial resolution of generated images
BATCH_SIZE        = 128      # Mini-batch size
Z_DIM             = 128      # Latent-space dimensionality
EPOCHS            = 15      # Training epochs
CRITIC_ITERATIONS = 3        # Critic updates per generator update
LAMBDA_GP         = 10       # Gradient penalty coefficient
LR                = 1e-4     # Learning rate for both networks
SUBSET_SIZE       = 15_000   # Training images sampled from the full dataset
DEVICE            = "cuda" if torch.cuda.is_available() else "cpu"

print(f"[Config] Device: {DEVICE} | Image size: {IMAGE_SIZE} | Z dim: {Z_DIM}")


# ─────────────────────────────────────────────
# 2. Dataset Download & Loading  (Kaggle)
# ─────────────────────────────────────────────
def setup_kaggle_and_download():
    """Upload kaggle.json, configure credentials, and download the dataset."""
    from google.colab import files           # Colab only
    files.upload()                           # Select kaggle.json

    os.makedirs(os.path.expanduser("~/.kaggle"), exist_ok=True)
    os.system("cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json")
    os.system("kaggle datasets download -d splcher/animefacedataset")
    os.system("unzip -q animefacedataset.zip -d data/")
    print("[Dataset] Download complete.")


def get_dataloader(root: str = "data/", subset_size: int = SUBSET_SIZE) -> DataLoader:
    """
    Build a DataLoader over a random subset of the anime-face dataset.

    Each image is:
      1. Resized to IMAGE_SIZE × IMAGE_SIZE
      2. Centre-cropped to IMAGE_SIZE × IMAGE_SIZE
      3. Converted to a tensor in [0, 1]
      4. Normalised to [-1, 1] (matching the Generator's Tanh output)
    """
    transform = transforms.Compose([
        transforms.Resize(IMAGE_SIZE),
        transforms.CenterCrop(IMAGE_SIZE),
        transforms.ToTensor(),
        transforms.Normalize([0.5] * 3, [0.5] * 3),   # → [-1, 1]
    ])

    full_dataset = ImageFolder(root=root, transform=transform)
    indices      = np.random.choice(len(full_dataset), subset_size, replace=False)
    dataset      = Subset(full_dataset, indices)

    print(f"[Dataset] Using {len(dataset)} / {len(full_dataset)} images.")

    return DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2,
        pin_memory=(DEVICE == "cuda"),
    )


# ─────────────────────────────────────────────
# 3. Model Architecture
# ─────────────────────────────────────────────

class Generator(nn.Module):

    def __init__(self, z_dim: int = Z_DIM):
        super().__init__()
        self.net = nn.Sequential(
            # Block 1 — 1×1 → 4×4
            nn.ConvTranspose2d(z_dim, 512, kernel_size=4, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(512),
            nn.ReLU(inplace=True),

            # Block 2 — 4×4 → 8×8
            nn.ConvTranspose2d(512, 256, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),

            # Block 3 — 8×8 → 16×16
            nn.ConvTranspose2d(256, 128, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),

            # Block 4 — 16×16 → 32×32
            nn.ConvTranspose2d(128, 64, kernel_size=4, stride=2, padding=1, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),

            # Block 5 — 32×32 → 64×64  (output)
            nn.ConvTranspose2d(64, 3, kernel_size=4, stride=2, padding=1, bias=False),
            nn.Tanh(),
        )

    def forward(self, z: torch.Tensor) -> torch.Tensor:
        return self.net(z)


class Critic(nn.Module):

    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            # Block 1 — 64×64 → 32×32  (no norm on first layer)
            nn.Conv2d(3, 64, kernel_size=4, stride=2, padding=1, bias=False),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 2 — 32×32 → 16×16
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(128, affine=True),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 3 — 16×16 → 8×8
            nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(256, affine=True),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 4 — 8×8 → 4×4
            nn.Conv2d(256, 512, kernel_size=4, stride=2, padding=1, bias=False),
            nn.InstanceNorm2d(512, affine=True),
            nn.LeakyReLU(0.2, inplace=True),

            # Block 5 — 4×4 → 1×1  (output score)
            nn.Conv2d(512, 1, kernel_size=4, stride=1, padding=0, bias=False),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x).view(-1)


# ─────────────────────────────────────────────
# 4. WGAN-GP Training Utilities
# ─────────────────────────────────────────────

def gradient_penalty(
    critic: nn.Module,
    real: torch.Tensor,
    fake: torch.Tensor,
    device: str = DEVICE,
) -> torch.Tensor:

    batch_size, C, H, W = real.shape
    eps           = torch.rand(batch_size, 1, 1, 1, device=device).expand_as(real)
    interpolated  = (eps * real + (1.0 - eps) * fake).requires_grad_(True)

    critic_out = critic(interpolated)

    grads = torch.autograd.grad(
        outputs=critic_out,
        inputs=interpolated,
        grad_outputs=torch.ones_like(critic_out),
        create_graph=True,
        retain_graph=True,
    )[0]                                         # shape: (N, C, H, W)

    grad_norm = grads.view(batch_size, -1).norm(2, dim=1)   # L2 norm per sample
    return ((grad_norm - 1.0) ** 2).mean()


def weights_init(module: nn.Module) -> None:

    classname = type(module).__name__
    if "Conv" in classname:
        nn.init.normal_(module.weight.data, 0.0, 0.02)
    elif "BatchNorm" in classname:
        nn.init.normal_(module.weight.data, 1.0, 0.02)
        nn.init.constant_(module.bias.data, 0.0)


# ─────────────────────────────────────────────
# 5. Training Loop
# ─────────────────────────────────────────────

def train(
    loader: DataLoader,
    generator: nn.Module,
    critic: nn.Module,
    opt_G: optim.Optimizer,
    opt_C: optim.Optimizer,
    fixed_noise: torch.Tensor,
    epochs: int = EPOCHS,
    device: str = DEVICE,
) -> dict:

    os.makedirs("outputs", exist_ok=True)
    history = {"loss_C": [], "loss_G": []}

    for epoch in range(epochs):
        epoch_loss_C, epoch_loss_G, n_batches = 0.0, 0.0, 0

        loop = tqdm(loader, desc=f"Epoch [{epoch+1}/{epochs}]", leave=True)

        for real, _ in loop:
            real          = real.to(device)
            cur_batch     = real.shape[0]

            # Critic update (CRITIC_ITERATIONS times)
            for _ in range(CRITIC_ITERATIONS):
                noise        = torch.randn(cur_batch, Z_DIM, 1, 1, device=device)
                fake         = generator(noise).detach()   # no generator grad needed

                loss_C = (
                    -(critic(real).mean() - critic(fake).mean())  # Wasserstein distance (negated)
                    + LAMBDA_GP * gradient_penalty(critic, real, fake, device)
                )

                opt_C.zero_grad()
                loss_C.backward()
                opt_C.step()

            # ── Generator update
            noise   = torch.randn(cur_batch, Z_DIM, 1, 1, device=device)
            fake    = generator(noise)
            loss_G  = -critic(fake).mean()

            opt_G.zero_grad()
            loss_G.backward()
            opt_G.step()

            epoch_loss_C += loss_C.item()
            epoch_loss_G += loss_G.item()
            n_batches    += 1

            loop.set_postfix(loss_C=f"{loss_C.item():.3f}", loss_G=f"{loss_G.item():.3f}")

        # Record epoch averages
        avg_C = epoch_loss_C / n_batches
        avg_G = epoch_loss_G / n_batches
        history["loss_C"].append(avg_C)
        history["loss_G"].append(avg_G)
        print(f"  → Avg loss_C: {avg_C:.4f} | Avg loss_G: {avg_G:.4f}")

        # Save sample grid
        with torch.no_grad():
            fake_samples = generator(fixed_noise)
        save_image(fake_samples, f"outputs/epoch_{epoch+1:02d}.png", normalize=True, nrow=8)

    return history


# ─────────────────────────────────────────────
# 6. Evaluation Metrics
# ─────────────────────────────────────────────

def get_inception_features(images: torch.Tensor, inception: nn.Module) -> np.ndarray:

    resize = transforms.Resize((299, 299), antialias=True)
    imgs   = resize((images + 1.0) / 2.0).clamp(0, 1)   # [-1,1] → [0,1]

    with torch.no_grad():
        features = inception(imgs)                       # (N, 2048)
    return features.cpu().numpy()


def inception_score(
    generator: nn.Module,
    n_samples: int = 5000,
    batch_size: int = 64,
    splits: int = 10,
    device: str = DEVICE,
) -> tuple[float, float]:

    print("[Eval] Computing Inception Score …")

    # InceptionV3 with softmax output
    inception = inception_v3(pretrained=True, transform_input=False).to(device).eval()
    inception.fc = nn.Identity()   # we want the final 1000-class logits, so restore
    inception    = inception_v3(pretrained=True, transform_input=False).to(device).eval()

    resize = transforms.Resize((299, 299), antialias=True)
    all_probs = []

    with torch.no_grad():
        for _ in range(math.ceil(n_samples / batch_size)):
            noise  = torch.randn(batch_size, Z_DIM, 1, 1, device=device)
            fake   = generator(noise)
            imgs   = resize((fake + 1.0) / 2.0).clamp(0, 1)
            logits = inception(imgs)
            probs  = torch.softmax(logits, dim=1).cpu().numpy()
            all_probs.append(probs)

    all_probs = np.concatenate(all_probs, axis=0)[:n_samples]  # (N, 1000)
    chunk_scores = []

    for k in range(splits):
        chunk = all_probs[k * (n_samples // splits) : (k + 1) * (n_samples // splits)]
        py    = chunk.mean(axis=0, keepdims=True)                      # marginal p(y)
        kl    = chunk * (np.log(chunk + 1e-10) - np.log(py + 1e-10))  # KL per image
        chunk_scores.append(np.exp(kl.sum(axis=1).mean()))

    mean_is, std_is = float(np.mean(chunk_scores)), float(np.std(chunk_scores))
    print(f"  IS = {mean_is:.3f} ± {std_is:.3f}")
    return mean_is, std_is


def compute_fid(
    generator: nn.Module,
    real_loader: DataLoader,
    n_fake: int = 5000,
    device: str = DEVICE,
) -> float:

    print("[Eval] Computing FID …")

    # InceptionV3 truncated at pool3 (2048-d features)
    inception = inception_v3(pretrained=True, transform_input=False).to(device).eval()
    inception.fc       = nn.Identity()
    inception.dropout  = nn.Identity()

    resize = transforms.Resize((299, 299), antialias=True)

    def extract_features(images: torch.Tensor) -> np.ndarray:
        imgs = resize((images + 1.0) / 2.0).clamp(0, 1).to(device)
        with torch.no_grad():
            feats = inception(imgs)
        return feats.cpu().numpy()

    # Real features
    real_feats = []
    for imgs, _ in real_loader:
        real_feats.append(extract_features(imgs))
        if len(np.concatenate(real_feats)) >= n_fake:
            break
    real_feats = np.concatenate(real_feats)[:n_fake]

    # Fake features
    fake_feats = []
    collected  = 0
    while collected < n_fake:
        batch  = min(64, n_fake - collected)
        noise  = torch.randn(batch, Z_DIM, 1, 1, device=device)
        fake   = generator(noise)
        fake_feats.append(extract_features(fake))
        collected += batch
    fake_feats = np.concatenate(fake_feats)[:n_fake]

    # Statistics
    mu_r, sigma_r = real_feats.mean(0), np.cov(real_feats, rowvar=False)
    mu_f, sigma_f = fake_feats.mean(0), np.cov(fake_feats, rowvar=False)

    # FID formula
    diff     = mu_r - mu_f
    cov_mean, _ = linalg.sqrtm(sigma_r @ sigma_f, disp=False)
    if np.iscomplexobj(cov_mean):
        cov_mean = cov_mean.real

    fid = float(diff @ diff + np.trace(sigma_r + sigma_f - 2.0 * cov_mean))
    print(f"  FID = {fid:.2f}")
    return fid


# ─────────────────────────────────────────────
# 7. Visualisation Helper
# ─────────────────────────────────────────────

def plot_loss_curves(history: dict, save_path: str = "outputs/loss_curves.png") -> None:
    """Plot critic and generator loss curves and save to disk."""
    try:
        import matplotlib.pyplot as plt

        epochs = range(1, len(history["loss_C"]) + 1)
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))

        axes[0].plot(epochs, history["loss_C"], label="Critic Loss", color="steelblue")
        axes[0].set_title("Critic Loss per Epoch")
        axes[0].set_xlabel("Epoch"); axes[0].set_ylabel("Loss")
        axes[0].legend(); axes[0].grid(True, alpha=0.3)

        axes[1].plot(epochs, history["loss_G"], label="Generator Loss", color="tomato")
        axes[1].set_title("Generator Loss per Epoch")
        axes[1].set_xlabel("Epoch"); axes[1].set_ylabel("Loss")
        axes[1].legend(); axes[1].grid(True, alpha=0.3)

        plt.tight_layout()
        plt.savefig(save_path, dpi=150)
        plt.close()
        print(f"[Viz] Loss curves saved → {save_path}")
    except ImportError:
        print("[Viz] matplotlib not available; skipping loss plot.")


# ─────────────────────────────────────────────
# 8. Main Entry Point
# ─────────────────────────────────────────────

def main():


    loader = get_dataloader(root="data/", subset_size=SUBSET_SIZE)

    G = Generator(Z_DIM).to(DEVICE)
    C = Critic().to(DEVICE)

    G.apply(weights_init)
    C.apply(weights_init)

    print(f"[Model] Generator params:  {sum(p.numel() for p in G.parameters()):,}")
    print(f"[Model] Critic params:     {sum(p.numel() for p in C.parameters()):,}")

    opt_G = optim.Adam(G.parameters(), lr=LR, betas=(0.0, 0.9))
    opt_C = optim.Adam(C.parameters(), lr=LR, betas=(0.0, 0.9))

    # Fixed noise for consistent progress tracking across epochs
    fixed_noise = torch.randn(32, Z_DIM, 1, 1, device=DEVICE)

    history = train(loader, G, C, opt_G, opt_C, fixed_noise, epochs=EPOCHS, device=DEVICE)

    torch.save(G.state_dict(), "generator.pth")
    torch.save(C.state_dict(), "critic.pth")
    print("[Checkpoint] Models saved → generator.pth, critic.pth")

    plot_loss_curves(history)

    G.eval()
    mean_is, std_is = inception_score(G, n_samples=5000, device=DEVICE)
    fid = compute_fid(G, loader, n_fake=5000, device=DEVICE)

    print("\n╔══════════════════════════════╗")
    print("║      Evaluation Results      ║")
    print("╠══════════════════════════════╣")
    print(f"║  Inception Score: {mean_is:.3f} ± {std_is:.3f}")
    print(f"║  FID Score:       {fid:.2f}")
    print("╚══════════════════════════════╝")

    # Save metrics to text file
    with open("outputs/metrics.txt", "w") as f:
        f.write(f"Inception Score: {mean_is:.4f} ± {std_is:.4f}\n")
        f.write(f"FID Score:       {fid:.4f}\n")
    print("[Eval] Metrics saved → outputs/metrics.txt")


if __name__ == "__main__":
    main()

